name: taxi_launcher
description: "A Flutter plugin which gives avaliable taxis options based on installed apps on device"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.taxi_launcher
        pluginClass: TaxiLauncherPlugin
      ios:
        pluginClass: TaxiLauncherPlugin

  assets:
    - assets/icons/
